---
- hosts: Dev
  become: true
  tasks:
  - name: Copy war file to remote nodes
    copy:
      src: ./abc_tech.war
      dest: /home/ubuntu
  - name: Copy Dockerfile to remote nodes
    copy:
      src: ./Dockerfile
      dest: /home/ubuntu
  - name: login to dockerhub
    docker_login:
      username: elhadje87
      password: "$Dembaba87"
  - name: build docker image
    command: docker build -t tech_app:v1 .
  - name: tag image
    command: docker tag tech_app:v1 elhadje87/tech_app:latest
  - name: push image
    command: docker push elhadje87/tech_app:latest

  - name: Check if container exists
    ansible.builtin.shell: docker ps -a -q -f name=mytech_app
    register: container_exists
    changed_when: false

  - name: Stop and remove existing container
    command: docker rm -f mytech_app
    when: container_exists.stdout != ""

  - name: creating docker container
    command: docker run -d --name mytech_app -P tech_app:v1
...